### ISSUE TITLE
Interpreter crashing

### ISSUE THREAD

**Issue by umnikos** [apankrat/bff#3] opened 2019-08-08 20:18 UTC
![Screenshot of the issue](https://user-images.githubusercontent.com/22576233/62734395-a2dbfa00-ba31-11e9-94ef-5e656164bfe2.png)

Brainf\*\*k code generated using [c2bf](https://github.com/arthaud/c2bf). All relevant files [in this gist.](https://gist.github.com/umnikos/613b757b7971aad0c529f990017da651)

I am looking for a workaround; The output generated is correct, I just don't want it to crash afterwards :smiley:

**Comment by apankrat** [comment] 2019-08-09 09:45
Can't reproduce this. More specifically, I am not seeing any malloc() calls around that point in execution.

Do this - add `printf("%p %zu\n", ptr, sz);` as the first line in `xalloc` and show me the output. This is what I get:

> alex@dev:~/src/bff$ cat input | ./bff a.bf
> (nil) 1025
> 0x13c8250 2049
> 0x13c8250 2657
> (nil) 62856
> (nil) 1024
> 1
> 0
> 1
> 0
> 1
> 0
> 1
> 0
> 1
> 0
> 1
> 0
> 1
> 0
> 1
> 0
> 1
> 0
> 1
> 0
> 1
> 0
> 1
> 0

and then it just sits there, presumably expecting further input.

**Comment by apankrat** [comment] 2019-08-09 10:03
Ah, nevermind. It should be exiting and it doesn't. Yeah, there's something funny going on.

**Comment by apankrat** [comment] 2019-08-09 10:46
OK, figured it out. Should be fixed with fb1fa456aca199266a038117363569f0a167b1f7.

Thanks for the report.

**Closed as completed by apankrat** 2019-08-09 10:46 UTC

**Comment by umnikos** [comment] 2019-08-10 20:20
Thanks for writing in the readme what caused the bug, I removed the leading >s and now it doesn't crash under 1.0.6
